export const books = [
  {
    _id: "621235e59540445b3sdfe9s0",
    name: "The Enchanted Chronicles",
    image: "/images/the_enchanted_chronicles.png",
    description:
      "Embark on a magical journey through The Enchanted Chronicles. Discover a world of mythical creatures, epic quests, and breathtaking adventures that will capture your imagination.",
    author: "Evelyn Sinclair",
    category: "Fantasy",
    price: 4.99,
    rating: 4.5,
    numReviews: 26,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: "636985e59540445b3c45e6af",
    name: "Digital Destiny",
    image: "/images/digital_destiny.png",
    description:
      "Enter the futuristic world of Digital Destiny, where virtual reality becomes a gateway to infinite possibilities. Join our protagonist as they navigate a virtual realm filled with danger, mystery, and unexpected alliances.",
    author: "Aiden Brooks",
    category: "Science Fiction",
    price: 9.99,
    rating: 4.2,
    numReviews: 10,
    isNew: false,
    reviews: [],
    stock: 5,
  },
  {
    _id: "6369860d9540445b3c45e6b1",
    name: "Love in Shadows",
    image: "/images/love_in_shadows.png",
    description:
      "Immerse yourself in the captivating world of Love in Shadows, a romantic tale of forbidden love, secret societies, and untold secrets. Follow the intertwined destinies of two souls as they navigate a world shrouded in darkness and intrigue.",
    author: "Sophia Parker",
    category: "Romance",
    price: 6.99,
    rating: 4.8,
    numReviews: 15,
    isNew: false,
    reviews: [],
    stock: 11,
  },
  {
    _id: "6369863c9540445b3c45e6b3",
    name: "The Lost Kingdom",
    image: "/images/lost_kingdom.png",
    description:
      "Step into The Lost Kingdom, a realm filled with ancient mysteries, hidden treasures, and powerful artifacts. Join our young protagonist on a quest to uncover the truth behind a long-forgotten civilization and protect the world from an impending darkness.",
    author: "Benjamin Anderson",
    category: "Adventure",
    price: 7.99,
    rating: 4.6,
    numReviews: 8,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  ,
  {
    _id: "636986749540445b3c45e6b7",
    name: "The Art of Time",
    image: "/images/art_of_time.png",
    description:
      "Immerse yourself in The Art of Time, a mesmerizing tale of time travel, destiny, and the power of choices. Join our protagonist as they navigate through different eras, encountering love, loss, and the timeless struggle between fate and free will.",
    author: "Gabriel Wells",
    category: "Science Fiction",
    price: 8.99,
    rating: 4.7,
    numReviews: 18,
    isNew: false,
    reviews: [],
    stock: 0,
  },
  {
    _id: "63804a5079636c2ced47757d",
    name: "Whispers in the Dark",
    image: "/images/whispers_in_the_dark.png",
    description:
      "Delve into the haunting world of Whispers in the Dark, a spine-chilling horror novel that will send shivers down your spine. Brace yourself for a sinister journey as you uncover the terrifying secrets lurking within the shadows.",
    author: "Victoria Blackwood",
    category: "Horror",
    price: 6.49,
    rating: 4.9,
    numReviews: 9,
    isNew: true,
    reviews: [],
    stock: 5,
  },
  {
    _id: "6381275e8e8648e00b7c82f7",
    name: "The Sound of Silence",
    image: "/images/sound_of_silence.png",
    description:
      "Experience The Sound of Silence, a poignant tale of love, loss, and the power of music. Follow the journey of a gifted musician as they navigate the complexities of relationships, find solace in their craft, and discover the healing power of sound.",
    author: "Julia Hartman",
    category: "Drama",
    price: 7.49,
    rating: 4.3,
    numReviews: 14,
    isNew: true,
    reviews: [],
    stock: 2,
  },
  {
    _id: "63895d3b2a3e062504353022",
    name: "Echoes of Eternity",
    image: "/images/echoes_of_eternity.png",
    description:
      "Enter a world of magic, destiny, and ancient prophecies in Echoes of Eternity. Join our young hero as they embark on a perilous quest to save their realm from an impending darkness that threatens to consume everything they hold dear.",
    author: "Jonathan Reed",
    category: "Fantasy",
    price: 7.99,
    rating: 4.6,
    numReviews: 11,
    isNew: true,
    reviews: [],
    stock: 49,
  },
];

export default books;
